# Generated by Django 4.2.2 on 2023-06-19 09:59

from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Post kategoriyasi',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fayl nomi')),
                ('is_created', models.DateField(auto_now=True, verbose_name='Yuklangan vaqti')),
                ('file', models.FileField(blank=True, help_text='Faylning maksimal hajmi 20Mb bo`lishi lozim!', upload_to='media/posts', validators=[user.validations.post_validator, user.validations.validate_file])),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Postlar',
            },
        ),
    ]
